name: ecopatrol_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # icon
  cupertino_icons: ^1.0.8

  # state management
  flutter_riverpod: ^2.5.0

  # local storage
  shared_preferences: ^2.3.2

  # db
  sqflite: ^2.3.0
  path: ^1.9.0

  # kamera
  image_picker: ^1.1.2

  # gps
  geolocator: ^11.0.0

  # permission
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true